### ISSUE TITLE
Running "rake" or "rake test" returns with error "File does not exist: extension"

### ISSUE THREAD

**Issue by jterhorst** [appsignal/c_from_ruby_example#2]
After calling the commands in the README and confirming the extension can compile and works with the commands provided, I attempted to run the included tests. They didn't run, instead giving the error "File does not exist: extension". I see that "extension.bundle" is generated after compilation, in the "ext" directory. Is there something else it needs?

I'm using ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin17.0] on macOS Mojave, with the latest Xcode tools.

**Comment by thijsc** [comment]
Thanks for reporting! I've tweaked the readme a bit in d1f73f10380acca875da5751d8c25e8daf613ce7, does it work for you that way?

**Comment by jterhorst** [comment]
That works great! Thank you!
